# Makefile.inc 
# Define the global variable for all submodules here

# Global CFLAGS
CFLAGS_global := -Wall -nostdlib -nostdinc -fno-builtin -fno-stack-protector 

# Global ASFLAGS
ASFLAGS := -felf

